# Generated by Django 5.1.3 on 2025-06-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="Your Company Name",
                        help_text="🏢 Company or organization name displayed throughout the site",
                        max_length=100,
                    ),
                ),
                (
                    "company_logo",
                    models.CharField(
                        default="/static/images/logo.png",
                        help_text="🖼️ Path to company logo image (e.g., /static/images/logo.png)",
                        max_length=200,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="📧 Primary contact email address",
                        max_length=100,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="📞 Contact phone number (e.g., +1 (555) 123-4567)",
                        max_length=20,
                    ),
                ),
                (
                    "contact_address",
                    models.TextField(
                        blank=True, help_text="📍 Physical address or location"
                    ),
                ),
                (
                    "social_facebook",
                    models.URLField(
                        blank=True, help_text="🔗 Facebook page URL"
                    ),
                ),
                (
                    "social_twitter",
                    models.URLField(
                        blank=True, help_text="🔗 Twitter/X profile URL"
                    ),
                ),
                (
                    "social_instagram",
                    models.URLField(
                        blank=True, help_text="🔗 Instagram profile URL"
                    ),
                ),
                (
                    "social_linkedin",
                    models.URLField(
                        blank=True, help_text="🔗 LinkedIn company page URL"
                    ),
                ),
                (
                    "social_youtube",
                    models.URLField(
                        blank=True, help_text="🔗 YouTube channel URL"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
