# Generated by Django 5.1.3 on 2025-06-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="footer_show_bottom_section",
            field=models.BooleanField(
                default=True, help_text="©️ Show copyright and legal links"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_show_footer",
            field=models.BooleanField(
                default=True, help_text="👇 Display footer section"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_show_logo",
            field=models.BooleanField(
                default=True, help_text="📷 Display company logo in footer"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_show_navigation",
            field=models.BooleanField(
                default=True, help_text="🧭 Show navigation menu in footer"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_show_tagline",
            field=models.BooleanField(
                default=True, help_text="💬 Show company tagline in footer"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_show_top_section",
            field=models.BooleanField(
                default=False,
                help_text="📋 Show company info and navigation in footer",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_background_transparent",
            field=models.BooleanField(
                default=False,
                help_text="🔍 Use transparent background with blur effect",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_is_sticky",
            field=models.BooleanField(
                default=True, help_text="📌 Keep header visible when scrolling"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_logo_alt",
            field=models.CharField(
                default="Logo",
                help_text="♿ Alt text for logo image (accessibility)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_show_company_name",
            field=models.BooleanField(
                default=False, help_text="🏢 Display company name next to logo"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_show_dark_mode_toggle",
            field=models.BooleanField(
                default=True, help_text="🌙 Show dark/light mode toggle button"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_show_login",
            field=models.BooleanField(
                default=True,
                help_text="👤 Show login button for unauthenticated users",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_show_logo",
            field=models.BooleanField(
                default=True, help_text="📷 Display company logo in header"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_show_signup",
            field=models.BooleanField(
                default=False,
                help_text="📝 Show signup button for unauthenticated users",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_type",
            field=models.CharField(
                choices=[
                    ("floating", "Floating Header"),
                    ("clean", "Clean Header"),
                    ("professional", "Professional Header"),
                    ("sidebar", "Sidebar Header"),
                ],
                default="professional",
                help_text="🎨 Choose the header layout style",
                max_length=20,
            ),
        ),
    ]
