# Generated by Django 5.1.3 on 2025-08-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_sitesettings_footer_show_bottom_section_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="company_logo_dark",
            field=models.URLField(
                blank=True,
                help_text="🌙 Logo for dark theme (upload via image upload below)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="company_logo_light",
            field=models.URLField(
                blank=True,
                help_text="🌞 Logo for light theme (upload via image upload below)",
                max_length=500,
            ),
        ),
    ]
