# Generated by Django 5.1.3 on 2025-08-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_sitesettings_company_logo_dark_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="favicon",
            field=models.URLField(
                blank=True,
                help_text="🔖 Favicon for browser tab (recommended: 32x32 or 16x16 PNG/ICO)",
                max_length=500,
            ),
        ),
    ]
