# Generated by Django 5.1.3 on 2025-08-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0004_sitesettings_favicon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="company_logo_dark",
            field=models.CharField(
                blank=True,
                help_text="🌙 Logo for dark theme (upload via image upload below)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="company_logo_light",
            field=models.CharField(
                blank=True,
                help_text="🌞 Logo for light theme (upload via image upload below)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="favicon",
            field=models.CharField(
                blank=True,
                help_text="🔖 Favicon for browser tab (recommended: 32x32 or 16x16 PNG/ICO)",
                max_length=500,
            ),
        ),
    ]
