# Generated by Django 5.1.3 on 2025-08-21 22:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Unique filename for URL generation (e.g., 'abc123.jpg')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original filename uploaded by user",
                        max_length=255,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        help_text="MIME type of the image (e.g., 'image/jpeg')",
                        max_length=100,
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(
                        help_text="File size in bytes"
                    ),
                ),
                (
                    "image_data",
                    models.BinaryField(
                        help_text="Actual image binary data stored in database"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "used_in_sections",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of section_ids where this image is used",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uploaded Image",
                "verbose_name_plural": "Uploaded Images",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["filename"],
                        name="images_uplo_filenam_163e2a_idx",
                    ),
                    models.Index(
                        fields=["-uploaded_at"],
                        name="images_uplo_uploade_47ee23_idx",
                    ),
                ],
            },
        ),
    ]
