# Generated by Django 5.1.3 on 2025-06-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="show_in_header",
            field=models.BooleanField(default=False),
        ),
    ]
