# Generated by Django 5.1.3 on 2025-06-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_page_show_in_header"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="✅ Check to make this page publicly accessible. Unchecked pages return 404.",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="📝 SEO meta description (max 160 chars). Appears in search results.",
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="🏷️ SEO title tag (max 60 chars). If empty, uses page title.",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="sections",
            field=models.JSONField(
                default=list,
                help_text='\n📋 SECTIONS CONFIGURATION GUIDE\n\n🔹 BASIC SECTION (Required):\n[\n  {\n    "id": "hero-section-1",\n    "component_type": "Hero1"\n  }\n]\n\n🔹 SECTION WITH STATIC BACKGROUND:\n[\n  {\n    "id": "hero-section-1", \n    "component_type": "Hero1",\n    "background": {\n      "type": "static",\n      "static_color": "accent",\n      "opacity": 0.3\n    }\n  }\n]\n\n🔹 SECTION WITH ANIMATED BACKGROUND:\n[\n  {\n    "id": "features-section-1",\n    "component_type": "Features1",\n    "background": {\n      "type": "animated",\n      "animated_type": "particles",\n      "opacity": 0.6\n    }\n  }\n]\n\n📖 FIELD REFERENCE:\n• id: Unique identifier (required)\n• component_type: Hero1, Features1, TestSection, etc. (required)\n• background: Optional styling configuration\n\n🎨 STATIC COLORS: background, muted, accent, secondary, primary, card\n🌟 ANIMATED TYPES: ripples, particles, waves, gradient\n💫 OPACITY: 0.0 (transparent) to 1.0 (solid)\n\n⚡ Background is completely optional - sections work with just id + component_type\n    ',
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="show_in_header",
            field=models.BooleanField(
                default=False,
                help_text="📍 Check to display this page as a link in the site navigation header.",
            ),
        ),
    ]
