# Generated by Django 5.1.3 on 2025-06-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_update_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="sections",
            field=models.JSONField(
                default=list,
                help_text='📋 SECTIONS CONFIGURATION GUIDE\n\n🔹 BASIC SECTION (Required):\n[\n  {\n    "id": "hero-section-1",\n    "component_type": "Hero1"\n  }\n]\n\n🔹 SECTION WITH STATIC BACKGROUND:\n[\n  {\n    "id": "hero-section-1", \n    "component_type": "Hero1",\n    "background": {\n      "type": "static",\n      "static_color": "accent",\n      "opacity": 0.3\n    }\n  }\n]\n\n🔹 SECTION WITH ANIMATED BACKGROUND:\n[\n  {\n    "id": "features-section-1",\n    "component_type": "Features1",\n    "background": {\n      "type": "animated",\n      "animated_type": "particles",\n      "opacity": 0.6\n    }\n  }\n]\n\n📖 FIELD REFERENCE:\n• id: Unique identifier (required)\n• component_type: Hero1, Features1, TestSection, etc. (required)  \n• background: Optional styling configuration\n\n🎨 STATIC COLORS: background, muted, accent, secondary, primary, card\n🌟 ANIMATED TYPES: ripples, particles, waves, gradient  \n💫 OPACITY: 0.0 (transparent) to 1.0 (solid)\n\n⚡ Background is completely optional - sections work with just id + component_type',
            ),
        ),
    ]
