# Generated by Django 5.1.3 on 2025-08-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_alter_page_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="header_order",
            field=models.IntegerField(
                default=0,
                help_text="🔢 Order position in header navigation (lower numbers appear first).",
            ),
        ),
    ]
