# Generated by Django 5.1.3 on 2025-10-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gold_exchange", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goldtransaction",
            name="user_token_account",
            field=models.CharField(
                blank=True,
                help_text="User's associated token account for sGOLD",
                max_length=88,
                null=True,
            ),
        ),
    ]
