# Generated by Django 5.1.3 on 2025-10-12 23:28

from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ("gold_exchange", "0002_alter_goldtransaction_user_token_account"),
    ]

    operations = [
        # Add profit_fee field to GoldTransaction
        migrations.AddField(
            model_name='goldtransaction',
            name='profit_fee',
            field=models.DecimalField(
                max_digits=20,
                decimal_places=9,
                default=Decimal('0'),
                help_text="Fee sent to profit wallet"
            ),
        ),
        # Add transaction_fee field to GoldTransaction
        migrations.AddField(
            model_name='goldtransaction',
            name='transaction_fee',
            field=models.DecimalField(
                max_digits=20,
                decimal_places=9,
                default=Decimal('0'),
                help_text="Transaction processing fee"
            ),
        ),
        # Add profit_fee field to ExchangeQuote
        migrations.AddField(
            model_name='exchangequote',
            name='profit_fee',
            field=models.DecimalField(
                max_digits=20,
                decimal_places=9,
                default=Decimal('0'),
                help_text="Fee sent to profit wallet"
            ),
        ),
        # Add transaction_fee field to ExchangeQuote
        migrations.AddField(
            model_name='exchangequote',
            name='transaction_fee',
            field=models.DecimalField(
                max_digits=20,
                decimal_places=9,
                default=Decimal('0'),
                help_text="Transaction processing fee"
            ),
        ),
    ]
