# Generated by Django 5.1.3 on 2025-06-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "section_id",
                    models.CharField(
                        help_text="Unique identifier for this section instance (e.g., 'hero-main', 'features-top')",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        default=dict,
                        help_text="JSON content for this section instance (titles, text, settings, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "ordering": ["section_id"],
            },
        ),
    ]
